#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
╔══════════════════════════════════════════════════════════════════════════╗
║                                                                          ║
║               S I L E N T   P R O   —   N E X U S   E D I T I O N        ║
║                         HỆ THỐNG ĐA NGÔN NGỮ — 20 NGÔN NGỮ               ║
║                                                                          ║
║  ⚠️  CHỈ DÙNG CHO MỤC ĐÍCH GIÁO DỤC & KIỂM TRA ĐƯỢC PHÉP                 ║
║  SỬ DỤNG TRÁI PHÉP LÀ BẤT HỢP PHÁP                                       ║
║                                                                          ║
╚══════════════════════════════════════════════════════════════════════════╝
"""

import os
import sys
import socket
import struct
import threading
import time
import random
import subprocess
import platform
import queue
from dataclasses import dataclass
from typing import List, Dict, Set, Optional, Tuple

# ═══════════════════════════════════════════════════════════════════════════
# HỆ THỐNG DỊCH — 20 NGÔN NGỮ
# ═══════════════════════════════════════════════════════════════════════════
class Language:
    CURRENT = "vi"

    # DANH SÁCH 20 NGÔN NGỮ
    LANGUAGES = {
        "vi": "🇻🇳 Tiếng Việt",
        "en": "🇺🇸 English",
        "zh": "🇨🇳 中文",
        "ja": "🇯🇵 日本語",
        "ko": "🇰🇷 한국어",
        "es": "🇪🇸 Español",
        "fr": "🇫🇷 Français",
        "de": "🇩🇪 Deutsch",
        "pt": "🇧🇷 Português",
        "ru": "🇷🇺 Русский",
        "ar": "🇸🇦 العربية",
        "th": "🇹🇭 ไทย",
        "id": "🇮🇩 Bahasa Indonesia",
        "ms": "🇲🇾 Bahasa Melayu",
        "hi": "🇮🇳 हिन्दी",
        "tr": "🇹🇷 Türkçe",
        "it": "🇮🇹 Italiano",
        "nl": "🇳🇱 Nederlands",
        "pl": "🇵🇱 Polski",
        "uk": "🇺🇦 Українська",
    }

    # BẢNG DỊCH
    TRANSLATIONS = {
        "vi": {
            "app_title": "S I L E N T   P R O   —   N E X U S   E D I T I O N",
            "subtitle": "Mã nguồn thuần • 500.000+ gói/giây • 12 Chế độ tấn công",
            "power_note": "⚡ 100 TRIỆU LẦN NHANH HƠN — KHÔNG DÙNG AIRCRACK • KHÔNG DÙNG MDK",
            "warning": "CHỈ DÙNG CHO MỤC ĐÍCH GIÁO DỤC & KIỂM TRA ĐƯỢC PHÉP",
            "illegal_use": "SỬ DỤNG TRÁI PHÉP LÀ BẤT HỢP PHÁP",
            "monitor": "CHẾ ĐỘ GIÁM SÁT",
            "interface": "GIAO DIỆN",
            "bluetooth": "BLUETOOTH",
            "wifi": "WIFI",
            "current_action": "HOẠT ĐỘNG HIỆN TẠI",
            "total_packets": "TỔNG GÓI ĐÃ GỬI",
            "active": "HOẠT ĐỘNG",
            "offline": "TẮT",
            "on": "BẬT",
            "restart_services": "🔄 Khởi động lại Dịch vụ Mạng & Bluetooth",
            "scan_wifi": "📡 Quét Mạng WiFi",
            "scan_bluetooth": "🔵 Quét Thiết bị Bluetooth",
            "deauth_single": "⚡ Ngắt Kết nối — Mục tiêu Đơn lẻ",
            "deauth_mega": "💀 Ngắt Kết nối — Chế độ Cực đại",
            "deauth_all": "💀💀💀 Ngắt Kết nối — TẤT CẢ Mạng",
            "multi_target": "🎯 Tấn công Đa mục tiêu",
            "auth_denial": "🔒 Từ chối Xác thực",
            "bluetooth_jam": "🔵 Gây nhiễu Bluetooth",
            "bluetooth_scan_jam": "🔵 Quét & Gây nhiễu Bluetooth",
            "install_deps": "📦 Cài đặt Thư viện Tùy chọn",
            "stop_all": "🛑 Dừng Tất cả & Dọn dẹp",
            "about": "ℹ Giới thiệu",
            "exit": "❌ Thoát",
            "select_lang": "🌐 CHỌN NGÔN NGỮ / SELECT LANGUAGE",
            "enter_choice": "Nhập lựa chọn",
            "press_enter": "Nhấn Enter để tiếp tục...",
            "success": "Thành công",
            "error": "Lỗi",
            "warning_msg": "Cảnh báo",
            "info": "Thông tin",
            "target": "Mục tiêu",
            "channel": "Kênh",
            "encryption": "Mã hóa",
            "name": "Tên",
            "mac": "Địa chỉ MAC",
            "ssid": "Tên mạng",
            "bssid": "BSSID",
            "signal": "Tín hiệu",
            "speed": "Tốc độ",
            "sent": "Đã gửi",
            "time": "Thời gian",
            "seconds": "giây",
            "packets": "gói",
            "pkt_s": "gói/s",
            "stop_attack": "Đang dừng tấn công...",
            "confirm_deauth_all": "⚠ NGẮT KẾT NỐI TẤT CẢ MẠNG? Nhập CÓ để xác nhận: ",
            "cancelled": "Đã hủy bỏ",
            "no_targets": "Không tìm thấy mục tiêu nào!",
            "invalid_choice": "Lựa chọn không hợp lệ",
            "select_target": "Chọn số thứ tự mục tiêu",
            "select_numbers": "Nhập số thứ tự cách nhau bằng dấu cách",
            "enter_mac": "Nhập địa chỉ MAC",
            "scanning": "Đang quét...",
            "found": "Tìm thấy",
            "networks": "mạng",
            "devices": "thiết bị",
            "no_networks": "Không tìm thấy mạng nào",
            "no_adapter": "Không phát hiện bộ điều hợp WiFi!",
            "enable_monitor_first": "Bật Chế độ Giám sát trước!",
            "monitor_mode_enabled": "Chế độ Giám sát — Đã bật",
            "monitor_mode_disabled": "Chế độ Giám sát — Đã tắt",
            "restarting_services": "Đang khởi động lại dịch vụ...",
            "done": "Hoàn thành!",
            "exiting": "Đang thoát...",
            "goodbye": "Tạm biệt! 🚀",
            "system_restored": "Hệ thống đã được khôi phục",
            "language_set": "Ngôn ngữ đã được đặt thành",
        },
        "en": {
            "app_title": "S I L E N T   P R O   —   N E X U S   E D I T I O N",
            "subtitle": "Pure Original Code • 500,000+ Packets/Sec • 12 Attack Modes",
            "power_note": "⚡ 100 MILLIONx MORE POWERFUL — NO AIRCRACK • NO MDK",
            "warning": "FOR EDUCATIONAL & AUTHORIZED TESTING ONLY",
            "illegal_use": "UNAUTHORIZED USE IS ILLEGAL",
            "monitor": "MONITOR MODE",
            "interface": "INTERFACE",
            "bluetooth": "BLUETOOTH",
            "wifi": "WIFI",
            "current_action": "CURRENT ACTION",
            "total_packets": "TOTAL PACKETS",
            "active": "ACTIVE",
            "offline": "OFFLINE",
            "on": "ON",
            "restart_services": "🔄 Restart Network & Bluetooth Services",
            "scan_wifi": "📡 Scan WiFi Networks",
            "scan_bluetooth": "🔵 Scan Bluetooth Devices",
            "deauth_single": "⚡ Deauth — Single Target",
            "deauth_mega": "💀 Deauth — MEGA Mode",
            "deauth_all": "💀💀💀 Deauth — ALL Networks",
            "multi_target": "🎯 Multi-Target Flood",
            "auth_denial": "🔒 Authentication Denial",
            "bluetooth_jam": "🔵 Bluetooth L2CAP Flood",
            "bluetooth_scan_jam": "🔵 Bluetooth Scan & Jam",
            "install_deps": "📦 Install Optional Dependencies",
            "stop_all": "🛑 Stop All & Clean Up",
            "about": "ℹ About",
            "exit": "❌ Exit",
            "select_lang": "🌐 SELECT LANGUAGE",
            "enter_choice": "Enter your choice",
            "press_enter": "Press Enter to continue...",
            "success": "Success",
            "error": "Error",
            "warning_msg": "Warning",
            "info": "Info",
            "target": "Target",
            "channel": "Channel",
            "encryption": "Encryption",
            "name": "Name",
            "mac": "MAC Address",
            "ssid": "SSID",
            "bssid": "BSSID",
            "signal": "Signal",
            "speed": "Speed",
            "sent": "Sent",
            "time": "Time",
            "seconds": "sec",
            "packets": "packets",
            "pkt_s": "pkt/s",
            "stop_attack": "Stopping attack...",
            "confirm_deauth_all": "⚠ DEAUTH EVERYTHING? Type YES to confirm: ",
            "cancelled": "Cancelled",
            "no_targets": "No targets found!",
            "invalid_choice": "Invalid choice",
            "select_target": "Select target number",
            "select_numbers": "Enter target numbers separated by space",
            "enter_mac": "Enter MAC address",
            "scanning": "Scanning...",
            "found": "Found",
            "networks": "networks",
            "devices": "devices",
            "no_networks": "No networks found",
            "no_adapter": "No WiFi adapter detected!",
            "enable_monitor_first": "Enable Monitor Mode first!",
            "monitor_mode_enabled": "Monitor Mode — ACTIVE",
            "monitor_mode_disabled": "Monitor Mode — DISABLED",
            "restarting_services": "Restarting services...",
            "done": "Complete!",
            "exiting": "Exiting...",
            "goodbye": "Goodbye! 🚀",
            "system_restored": "System restored",
            "language_set": "Language set to",
        },
        "zh": {
            "app_title": "S I L E N T   P R O   —   N E X U S   E D I T I O N",
            "subtitle": "纯原创代码 • 每秒50万+数据包 • 12种攻击模式",
            "power_note": "⚡ 强大1亿倍 — 无需AIRCRACK • 无需MDK",
            "warning": "仅用于教育和授权测试",
            "illegal_use": "未经授权使用属于违法行为",
            "monitor": "监听模式",
            "interface": "接口",
            "bluetooth": "蓝牙",
            "wifi": "无线网络",
            "current_action": "当前操作",
            "total_packets": "总发送包数",
            "active": "运行中",
            "offline": "已关闭",
            "on": "开启",
            "restart_services": "🔄 重启网络和蓝牙服务",
            "scan_wifi": "📡 扫描WiFi网络",
            "scan_bluetooth": "🔵 扫描蓝牙设备",
            "deauth_single": "⚡ 断开连接 — 单个目标",
            "deauth_mega": "💀 断开连接 — 超级模式",
            "deauth_all": "💀💀💀 断开连接 — 所有网络",
            "multi_target": "🎯 多目标攻击",
            "auth_denial": "🔒 拒绝认证",
            "bluetooth_jam": "🔵 蓝牙干扰攻击",
            "bluetooth_scan_jam": "🔵 扫描并干扰蓝牙",
            "install_deps": "📦 安装可选依赖",
            "stop_all": "🛑 停止所有并清理",
            "about": "ℹ 关于",
            "exit": "❌ 退出",
            "select_lang": "🌐 选择语言",
            "enter_choice": "请输入选择",
            "press_enter": "按回车键继续...",
            "success": "成功",
            "error": "错误",
            "warning_msg": "警告",
            "info": "信息",
            "target": "目标",
            "channel": "信道",
            "encryption": "加密",
            "name": "名称",
            "mac": "MAC地址",
            "ssid": "网络名称",
            "bssid": "BSSID",
            "signal": "信号",
            "speed": "速度",
            "sent": "已发送",
            "time": "时间",
            "seconds": "秒",
            "packets": "包",
            "pkt_s": "包/秒",
            "stop_attack": "正在停止攻击...",
            "confirm_deauth_all": "⚠ 断开所有网络连接？输入YES确认：",
            "cancelled": "已取消",
            "no_targets": "未找到目标！",
            "invalid_choice": "无效选择",
            "select_target": "选择目标编号",
            "select_numbers": "输入目标编号，用空格分隔",
            "enter_mac": "输入MAC地址",
            "scanning": "正在扫描...",
            "found": "找到",
            "networks": "个网络",
            "devices": "个设备",
            "no_networks": "未找到任何网络",
            "no_adapter": "未检测到WiFi适配器！",
            "enable_monitor_first": "请先启用监听模式！",
            "monitor_mode_enabled": "监听模式 — 已启用",
            "monitor_mode_disabled": "监听模式 — 已关闭",
            "restarting_services": "正在重启服务...",
            "done": "完成！",
            "exiting": "正在退出...",
            "goodbye": "再见！🚀",
            "system_restored": "系统已恢复",
            "language_set": "语言已设置为",
        },
        "ja": {
            "app_title": "S I L E N T   P R O   —   N E X U S   E D I T I O N",
            "subtitle": "純正オリジナルコード • 毎秒50万+パケット • 12の攻撃モード",
            "power_note": "⚡ 1億倍強力 — AIRCRACK不要 • MDK不要",
            "warning": "教育および許可されたテスト専用",
            "illegal_use": "許可なしの使用は違法です",
            "monitor": "モニターモード",
            "interface": "インターフェース",
            "bluetooth": "Bluetooth",
            "wifi": "WiFi",
            "current_action": "現在の動作",
            "total_packets": "送信済みパケット合計",
            "active": "アクティブ",
            "offline": "オフライン",
            "on": "オン",
            "restart_services": "🔄 ネットワークとBluetoothサービスを再起動",
            "scan_wifi": "📡 WiFiネットワークをスキャン",
            "scan_bluetooth": "🔵 Bluetoothデバイスをスキャン",
            "deauth_single": "⚡ 切断 — 単一ターゲット",
            "deauth_mega": "💀 切断 — メガモード",
            "deauth_all": "💀💀💀 切断 — すべてのネットワーク",
            "multi_target": "🎯 複数ターゲット攻撃",
            "auth_denial": "🔒 認証拒否",
            "bluetooth_jam": "🔵 Bluetoothジャミング",
            "bluetooth_scan_jam": "🔵 スキャンしてジャミング",
            "install_deps": "📦 オプション依存関係をインストール",
            "stop_all": "🛑 すべて停止してクリーンアップ",
            "about": "ℹ バージョン情報",
            "exit": "❌ 終了",
            "select_lang": "🌐 言語を選択",
            "enter_choice": "選択を入力",
            "press_enter": "Enterキーを押して続行...",
            "success": "成功",
            "error": "エラー",
            "warning_msg": "警告",
            "info": "情報",
            "target": "ターゲット",
            "channel": "チャネル",
            "encryption": "暗号化",
            "name": "名前",
            "mac": "MACアドレス",
            "ssid": "SSID",
            "bssid": "BSSID",
            "signal": "信号強度",
            "speed": "速度",
            "sent": "送信済み",
            "time": "時間",
            "seconds": "秒",
            "packets": "パケット",
            "pkt_s": "パケット/秒",
            "stop_attack": "攻撃を停止中...",
            "confirm_deauth_all": "⚠ すべてのネットワークを切断しますか？YESと入力して確認：",
            "cancelled": "キャンセルされました",
            "no_targets": "ターゲットが見つかりません！",
            "invalid_choice": "無効な選択",
            "select_target": "ターゲット番号を選択",
            "select_numbers": "スペース区切りで番号を入力",
            "enter_mac": "MACアドレスを入力",
            "scanning": "スキャン中...",
            "found": "見つかりました",
            "networks": "ネットワーク",
            "devices": "デバイス",
            "no_networks": "ネットワークが見つかりません",
            "no_adapter": "WiFiアダプターが検出されません！",
            "enable_monitor_first": "先にモニターモードを有効にしてください！",
            "monitor_mode_enabled": "モニターモード — 有効",
            "monitor_mode_disabled": "モニターモード — 無効",
            "restarting_services": "サービスを再起動中...",
            "done": "完了！",
            "exiting": "終了しています...",
            "goodbye": "さようなら！🚀",
            "system_restored": "システムを復元しました",
            "language_set": "言語を設定しました：",
        },
        "ko": {
            "app_title": "S I L E N T   P R O   —   N E X U S   E D I T I O N",
            "subtitle": "순수 오리지널 코드 • 초당 50만+ 패킷 • 12가지 공격 모드",
            "power_note": "⚡ 1억 배 더 강력 — AIRCRACK 불필요 • MDK 불필요",
            "warning": "교육 및 승인된 테스트 전용",
            "illegal_use": "무단 사용은 불법입니다",
            "monitor": "모니터 모드",
            "interface": "인터페이스",
            "bluetooth": "블루투스",
            "wifi": "와이파이",
            "current_action": "현재 작업",
            "total_packets": "총 전송된 패킷",
            "active": "활성",
            "offline": "비활성",
            "on": "켜짐",
            "restart_services": "🔄 네트워크 및 블루투스 서비스 재시작",
            "scan_wifi": "📡 와이파이 네트워크 스캔",
            "scan_bluetooth": "🔵 블루투스 기기 스캔",
            "deauth_single": "⚡ 연결 끊기 — 단일 대상",
            "deauth_mega": "💀 연결 끊기 — 메가 모드",
            "deauth_all": "💀💀💀 연결 끊기 — 전체 네트워크",
            "multi_target": "🎯 다중 대상 공격",
            "auth_denial": "🔒 인증 거부",
            "bluetooth_jam": "🔵 블루투스 간섭 공격",
            "bluetooth_scan_jam": "🔵 스캔 후 간섭 공격",
            "install_deps": "📦 선택적 의존성 설치",
            "stop_all": "🛑 모두 중지 및 정리",
            "about": "ℹ 정보",
            "exit": "❌ 종료",
            "select_lang": "🌐 언어 선택",
            "enter_choice": "선택을 입력하세요",
            "press_enter": "계속하려면 Enter 키를 누르세요...",
            "success": "성공",
            "error": "오류",
            "warning_msg": "경고",
            "info": "정보",
            "target": "대상",
            "channel": "채널",
            "encryption": "암호화",
            "name": "이름",
            "mac": "MAC 주소",
            "ssid": "SSID",
            "bssid": "BSSID",
            "signal": "신호",
            "speed": "속도",
            "sent": "전송됨",
            "time": "시간",
            "seconds": "초",
            "packets": "패킷",
            "pkt_s": "패킷/초",
            "stop_attack": "공격을 중지하는 중...",
            "confirm_deauth_all": "⚠ 모든 네트워크 연결을 끊으시겠습니까? YES 입력 후 확인:",
            "cancelled": "취소됨",
            "no_targets": "대상을 찾을 수 없습니다!",
            "invalid_choice": "잘못된 선택",
            "select_target": "대상 번호 선택",
            "select_numbers": "공백으로 구분하여 번호 입력",
            "enter_mac": "MAC 주소 입력",
            "scanning": "스캔 중...",
            "found": "찾음",
            "networks": "네트워크",
            "devices": "기기",
            "no_networks": "네트워크를 찾을 수 없습니다",
            "no_adapter": "와이파이 어댑터가 감지되지 않았습니다!",
            "enable_monitor_first": "모니터 모드를 먼저 활성화하세요!",
            "monitor_mode_enabled": "모니터 모드 — 활성화됨",
            "monitor_mode_disabled": "모니터 모드 — 비활성화됨",
            "restarting_services": "서비스를 재시작하는 중...",
            "done": "완료!",
            "exiting": "종료하는 중...",
            "goodbye": "안녕히 가세요! 🚀",
            "system_restored": "시스템이 복원되었습니다",
            "language_set": "언어가 설정되었습니다: ",
        },
        "es": {
            "app_title": "S I L E N T   P R O   —   N E X U S   E D I T I O N",
            "subtitle": "Código Original Puro • 500.000+ Paquetes/seg • 12 Modos de Ataque",
            "power_note": "⚡ 100 MILLONES de veces más potente — SIN AIRCRACK • SIN MDK",
            "warning": "SOLO PARA USO EDUCATIVO Y PRUEBAS AUTORIZADAS",
            "illegal_use": "EL USO SIN AUTORIZACIÓN ES ILEGAL",
            "monitor": "MODO MONITOR",
            "interface": "INTERFAZ",
            "bluetooth": "BLUETOOTH",
            "wifi": "WIFI",
            "current_action": "ACCIÓN ACTUAL",
            "total_packets": "TOTAL PAQUETES",
            "active": "ACTIVO",
            "offline": "DESCONECTADO",
            "on": "ENCENDIDO",
            "restart_services": "🔄 Reiniciar Servicios de Red y Bluetooth",
            "scan_wifi": "📡 Escanear Redes WiFi",
            "scan_bluetooth": "🔵 Escanear Dispositivos Bluetooth",
            "deauth_single": "⚡ Desconectar — Objetivo Único",
            "deauth_mega": "💀 Desconectar — Modo MEGA",
            "deauth_all": "💀💀💀 Desconectar — TODAS las Redes",
            "multi_target": "🎯 Ataque Multitarget",
            "auth_denial": "🔒 Denegación de Autenticación",
            "bluetooth_jam": "🔵 Inundación L2CAP Bluetooth",
            "bluetooth_scan_jam": "🔵 Escanear y Bloquear Bluetooth",
            "install_deps": "📦 Instalar Dependencias Opcionales",
            "stop_all": "🛑 Detener Todo y Limpiar",
            "about": "ℹ Acerca de",
            "exit": "❌ Salir",
            "select_lang": "🌐 SELECCIONAR IDIOMA",
            "enter_choice": "Ingrese su opción",
            "press_enter": "Presione Enter para continuar...",
            "success": "Éxito",
            "error": "Error",
            "warning_msg": "Advertencia",
            "info": "Información",
            "target": "Objetivo",
            "channel": "Canal",
            "encryption": "Cifrado",
            "name": "Nombre",
            "mac": "Dirección MAC",
            "ssid": "SSID",
            "bssid": "BSSID",
            "signal": "Señal",
            "speed": "Velocidad",
            "sent": "Enviados",
            "time": "Tiempo",
            "seconds": "seg",
            "packets": "paquetes",
            "pkt_s": "paq/s",
            "stop_attack": "Deteniendo ataque...",
            "confirm_deauth_all": "⚠ ¿DESCONECTAR TODO? Escriba YES para confirmar: ",
            "cancelled": "Cancelado",
            "no_targets": "¡No se encontraron objetivos!",
            "invalid_choice": "Opción inválida",
            "select_target": "Seleccione número de objetivo",
            "select_numbers": "Ingrese números separados por espacio",
            "enter_mac": "Ingrese dirección MAC",
            "scanning": "Escaneando...",
            "found": "Encontrados",
            "networks": "redes",
            "devices": "dispositivos",
            "no_networks": "No se encontraron redes",
            "no_adapter": "¡No se detectó adaptador WiFi!",
            "enable_monitor_first": "¡Habilite el Modo Monitor primero!",
            "monitor_mode_enabled": "Modo Monitor — ACTIVO",
            "monitor_mode_disabled": "Modo Monitor — DESACTIVADO",
            "restarting_services": "Reiniciando servicios...",
            "done": "¡Completado!",
            "exiting": "Saliendo...",
            "goodbye": "¡Adiós! 🚀",
            "system_restored": "Sistema restaurado",
            "language_set": "Idioma establecido a: ",
        },
        "fr": {
            "app_title": "S I L E N T   P R O   —   N E X U S   E D I T I O N",
            "subtitle": "Code Original Pur • 500 000+ Paquets/sec • 12 Modes d'Attaque",
            "power_note": "⚡ 100 MILLIONS de fois plus puissant — SANS AIRCRACK • SANS MDK",
            "warning": "UNIQUEMENT À DES FINS ÉDUCATIVES ET TESTS AUTORISÉS",
            "illegal_use": "L'USAGE NON AUTORISÉ EST ILLÉGAL",
            "monitor": "MODE MONITEUR",
            "interface": "INTERFACE",
            "bluetooth": "BLUETOOTH",
            "wifi": "WIFI",
            "current_action": "ACTION EN COURS",
            "total_packets": "TOTAL PAQUETS",
            "active": "ACTIF",
            "offline": "HORS LIGNE",
            "on": "ACTIVÉ",
            "restart_services": "🔄 Redémarrer les Services Réseau et Bluetooth",
            "scan_wifi": "📡 Scanner les Réseaux WiFi",
            "scan_bluetooth": "🔵 Scanner les Appareils Bluetooth",
            "deauth_single": "⚡ Déconnexion — Cible Unique",
            "deauth_mega": "💀 Déconnexion — Mode MEGA",
            "deauth_all": "💀💀💀 Déconnexion — TOUS les Réseaux",
            "multi_target": "🎯 Attaque Multicible",
            "auth_denial": "🔒 Rejet d'Authentification",
            "bluetooth_jam": "🔵 Inondation L2CAP Bluetooth",
            "bluetooth_scan_jam": "🔵 Scanner et Brouiller Bluetooth",
            "install_deps": "📦 Installer les Dépendances Optionnelles",
            "stop_all": "🛑 Tout Arrêter et Nettoyer",
            "about": "ℹ À propos",
            "exit": "❌ Quitter",
            "select_lang": "🌐 CHOISIR LA LANGUE",
            "enter_choice": "Entrez votre choix",
            "press_enter": "Appuyez sur Entrée pour continuer...",
            "success": "Succès",
            "error": "Erreur",
            "warning_msg": "Avertissement",
            "info": "Information",
            "target": "Cible",
            "channel": "Canal",
            "encryption": "Chiffrement",
            "name": "Nom",
            "mac": "Adresse MAC",
            "ssid": "SSID",
            "bssid": "BSSID",
            "signal": "Signal",
            "speed": "Vitesse",
            "sent": "Envoyés",
            "time": "Temps",
            "seconds": "sec",
            "packets": "paquets",
            "pkt_s": "paq/s",
            "stop_attack": "Arrêt de l'attaque...",
            "confirm_deauth_all": "⚠ DÉCONNECTER TOUT ? Tapez YES pour confirmer : ",
            "cancelled": "Annulé",
            "no_targets": "Aucune cible trouvée !",
            "invalid_choice": "Choix invalide",
            "select_target": "Sélectionnez le numéro de la cible",
            "select_numbers": "Entrez les numéros séparés par un espace",
            "enter_mac": "Entrez l'adresse MAC",
            "scanning": "Analyse en cours...",
            "found": "Trouvé",
            "networks": "réseaux",
            "devices": "appareils",
            "no_networks": "Aucun réseau trouvé",
            "no_adapter": "Aucun adaptateur WiFi détecté !",
            "enable_monitor_first": "Activez le Mode Moniteur d'abord !",
            "monitor_mode_enabled": "Mode Moniteur — ACTIF",
            "monitor_mode_disabled": "Mode Moniteur — DÉSACTIVÉ",
            "restarting_services": "Redémarrage des services...",
            "done": "Terminé !",
            "exiting": "Fermeture...",
            "goodbye": "Au revoir ! 🚀",
            "system_restored": "Système restauré",
            "language_set": "Langue définie sur : ",
        },
        "de": {
            "app_title": "S I L E N T   P R O   —   N E X U S   E D I T I O N",
            "subtitle": "Reiner Originalcode • 500.000+ Pakete/Sek • 12 Angriffsmodi",
            "power_note": "⚡ 100 MILLIONEN Mal Stärker — KEIN AIRCRACK • KEIN MDK",
            "warning": "NUR FÜR BILDUNGSZWECKE UND AUTORISIERTE TESTS",
            "illegal_use": "UNBEFUGTE NUTZUNG IST STRAFBAR",
            "monitor": "MONITORMODUS",
            "interface": "SCHNITTSTELLE",
            "bluetooth": "BLUETOOTH",
            "wifi": "WIFI",
            "current_action": "AKTUELLE AKTION",
            "total_packets": "GESAMTPAKETE",
            "active": "AKTIV",
            "offline": "OFFLINE",
            "on": "EINGESCHALTET",
            "restart_services": "🔄 Netzwerk- und Bluetooth-Dienste neu starten",
            "scan_wifi": "📡 WLAN-Netzwerke scannen",
            "scan_bluetooth": "🔵 Bluetooth-Geräte scannen",
            "deauth_single": "⚡ Trennen — Einzelziel",
            "deauth_mega": "💀 Trennen — MEGA-Modus",
            "deauth_all": "💀💀💀 Trennen — ALLE Netzwerke",
            "multi_target": "🎯 Mehrziel-Angriff",
            "auth_denial": "🔒 Authentifizierungs-Verweigerung",
            "bluetooth_jam": "🔵 Bluetooth L2CAP-Flutangriff",
            "bluetooth_scan_jam": "🔵 Scannen & Stören von Bluetooth",
            "install_deps": "📦 Optionale Abhängigkeiten installieren",
            "stop_all": "🛑 Alles Stoppen & Aufräumen",
            "about": "ℹ Über",
            "exit": "❌ Beenden",
            "select_lang": "🌐 SPRACHE WÄHLEN",
            "enter_choice": "Auswahl eingeben",
            "press_enter": "Enter drücken zum Weiterfahren...",
            "success": "Erfolg",
            "error": "Fehler",
            "warning_msg": "Warnung",
            "info": "Information",
            "target": "Ziel",
            "channel": "Kanal",
            "encryption": "Verschlüsselung",
            "name": "Name",
            "mac": "MAC-Adresse",
            "ssid": "SSID",
            "bssid": "BSSID",
            "signal": "Signal",
            "speed": "Geschwindigkeit",
            "sent": "Gesendet",
            "time": "Zeit",
            "seconds": "sek",
            "packets": "Pakete",
            "pkt_s": "Pakete/s",
            "stop_attack": "Angriff wird gestoppt...",
            "confirm_deauth_all": "⚠ ALLES TRENNEN? YES eingeben zum Bestätigen: ",
            "cancelled": "Abgebrochen",
            "no_targets": "Keine Ziele gefunden!",
            "invalid_choice": "Ungültige Auswahl",
            "select_target": "Zielnummer wählen",
            "select_numbers": "Nummern durch Leerzeichen getrennt eingeben",
            "enter_mac": "MAC-Adresse eingeben",
            "scanning": "Scannen...",
            "found": "Gefunden",
            "networks": "Netzwerke",
            "devices": "Geräte",
            "no_networks": "Keine Netzwerke gefunden",
            "no_adapter": "Kein WLAN-Adapter erkannt!",
            "enable_monitor_first": "Zuerst Monitor-Modus aktivieren!",
            "monitor_mode_enabled": "Monitor-Modus — AKTIV",
            "monitor_mode_disabled": "Monitor-Modus — INAKTIV",
            "restarting_services": "Dienste werden neu gestartet...",
            "done": "Fertig!",
            "exiting": "Beenden...",
            "goodbye": "Auf Wiedersehen! 🚀",
            "system_restored": "System wiederhergestellt",
            "language_set": "Sprache eingestellt auf: ",
        },
        "pt": {
            "app_title": "S I L E N T   P R O   —   N E X U S   E D I T I O N",
            "subtitle": "Código Original Puro • 500.000+ Pacotes/seg • 12 Modos de Ataque",
            "power_note": "⚡ 100 MILHÕES de vezes mais poderoso — SEM AIRCRACK • SEM MDK",
            "warning": "APENAS PARA USO EDUCACIONAL E TESTES AUTORIZADOS",
            "illegal_use": "O USO NÃO AUTORIZADO É ILEGAL",
            "monitor": "MODO MONITOR",
            "interface": "INTERFACE",
            "bluetooth": "BLUETOOTH",
            "wifi": "WIFI",
            "current_action": "AÇÃO ATUAL",
            "total_packets": "TOTAL DE PACOTES",
            "active": "ATIVO",
            "offline": "DESCONECTADO",
            "on": "LIGADO",
            "restart_services": "🔄 Reiniciar Serviços de Rede e Bluetooth",
            "scan_wifi": "📡 Procurar Redes WiFi",
            "scan_bluetooth": "🔵 Procurar Dispositivos Bluetooth",
            "deauth_single": "⚡ Desconectar — Alvo Único",
            "deauth_mega": "💀 Desconectar — Modo MEGA",
            "deauth_all": "💀💀💀 Desconectar — TODAS as Redes",
            "multi_target": "🎯 Ataque Multi-Alvo",
            "auth_denial": "🔒 Negação de Autenticação",
            "bluetooth_jam": "🔵 Inundação L2CAP Bluetooth",
            "bluetooth_scan_jam": "🔵 Procurar e Bloquear Bluetooth",
            "install_deps": "📦 Instalar Dependências Opcionais",
            "stop_all": "🛑 Parar Tudo e Limpar",
            "about": "ℹ Sobre",
            "exit": "❌ Sair",
            "select_lang": "🌐 SELECIONAR IDIOMA",
            "enter_choice": "Digite sua opção",
            "press_enter": "Pressione Enter para continuar...",
            "success": "Sucesso",
            "error": "Erro",
            "warning_msg": "Aviso",
            "info": "Informação",
            "target": "Alvo",
            "channel": "Canal",
            "encryption": "Criptografia",
            "name": "Nome",
            "mac": "Endereço MAC",
            "ssid": "SSID",
            "bssid": "BSSID",
            "signal": "Sinal",
            "speed": "Velocidade",
            "sent": "Enviados",
            "time": "Tempo",
            "seconds": "seg",
            "packets": "pacotes",
            "pkt_s": "pac/s",
            "stop_attack": "Parando ataque...",
            "confirm_deauth_all": "⚠ DESCONECTAR TUDO? Digite YES para confirmar: ",
            "cancelled": "Cancelado",
            "no_targets": "Nenhum alvo encontrado!",
            "invalid_choice": "Opção inválida",
            "select_target": "Selecione o número do alvo",
            "select_numbers": "Digite os números separados por espaço",
            "enter_mac": "Digite o endereço MAC",
            "scanning": "Procurando...",
            "found": "Encontrados",
            "networks": "redes",
            "devices": "dispositivos",
            "no_networks": "Nenhuma rede encontrada",
            "no_adapter": "Adaptador WiFi não detectado!",
            "enable_monitor_first": "Ative o Modo Monitor primeiro!",
            "monitor_mode_enabled": "Modo Monitor — ATIVO",
            "monitor_mode_disabled": "Modo Monitor — DESATIVADO",
            "restarting_services": "Reiniciando serviços...",
            "done": "Concluído!",
            "exiting": "Saindo...",
            "goodbye": "Adeus! 🚀",
            "system_restored": "Sistema restaurado",
            "language_set": "Idioma definido para: ",
        },
        "ru": {
            "app_title": "S I L E N T   P R O   —   N E X U S   E D I T I O N",
            "subtitle": "Чистый Оригинальный Код • 500 000+ Пакетов/сек • 12 Режимов Атаки",
            "power_note": "⚡ В 100 МИЛЛИОНОВ РАЗ Мощнее — БЕЗ AIRCRACK • БЕЗ MDK",
            "warning": "ТОЛЬКО ДЛЯ ОБУЧЕНИЯ И АВТОРИЗОВАННЫХ ТЕСТОВ",
            "illegal_use": "НЕСАНКЦИОНИРОВАННОЕ ИСПОЛЬЗОВАНИЕ НЕЗАКОННО",
            "monitor": "РЕЖИМ МОНИТОРА",
            "interface": "ИНТЕРФЕЙС",
            "bluetooth": "БЛЮТУЗ",
            "wifi": "WIFI",
            "current_action": "ТЕКУЩЕЕ ДЕЙСТВИЕ",
            "total_packets": "ВСЕГО ПАКЕТОВ",
            "active": "АКТИВЕН",
            "offline": "ОТКЛЮЧЕН",
            "on": "ВКЛЮЧЕН",
            "restart_services": "🔄 Перезапустить Сетевые и Bluetooth Службы",
            "scan_wifi": "📡 Сканировать WiFi Сети",
            "scan_bluetooth": "🔵 Сканировать Bluetooth Устройства",
            "deauth_single": "⚡ Отключить — Одиночная Цель",
            "deauth_mega": "💀 Отключить — Режим МЕГА",
            "deauth_all": "💀💀💀 Отключить — ВСЕ Сети",
            "multi_target": "🎯 Атака по Множеству Целей",
            "auth_denial": "🔒 Отказ Аутентификации",
            "bluetooth_jam": "🔵 L2CAP-Флуд Bluetooth",
            "bluetooth_scan_jam": "🔵 Сканировать и Заглушить Bluetooth",
            "install_deps": "📦 Установить Дополнительные Зависимости",
            "stop_all": "🛑 Остановить Всё и Очистить",
            "about": "ℹ О программе",
            "exit": "❌ Выход",
            "select_lang": "🌐 ВЫБРАТЬ ЯЗЫК",
            "enter_choice": "Введите ваш выбор",
            "press_enter": "Нажмите Enter для продолжения...",
            "success": "Успешно",
            "error": "Ошибка",
            "warning_msg": "Предупреждение",
            "info": "Информация",
            "target": "Цель",
            "channel": "Канал",
            "encryption": "Шифрование",
            "name": "Имя",
            "mac": "MAC-Адрес",
            "ssid": "SSID",
            "bssid": "BSSID",
            "signal": "Сигнал",
            "speed": "Скорость",
            "sent": "Отправлено",
            "time": "Время",
            "seconds": "сек",
            "packets": "пакетов",
            "pkt_s": "пак/сек",
            "stop_attack": "Остановка атаки...",
            "confirm_deauth_all": "⚠ ОТКЛЮЧИТЬ ВСЁ? Введите YES для подтверждения: ",
            "cancelled": "Отменено",
            "no_targets": "Целей не найдено!",
            "invalid_choice": "Неверный выбор",
            "select_target": "Выберите номер цели",
            "select_numbers": "Введите номера через пробел",
            "enter_mac": "Введите MAC-адрес",
            "scanning": "Сканирование...",
            "found": "Найдено",
            "networks": "сетей",
            "devices": "устройств",
            "no_networks": "Сетей не найдено",
            "no_adapter": "WiFi адаптер не обнаружен!",
            "enable_monitor_first": "Сначала включите Режим Монитора!",
            "monitor_mode_enabled": "Режим Монитора — АКТИВЕН",
            "monitor_mode_disabled": "Режим Монитора — ОТКЛЮЧЕН",
            "restarting_services": "Перезапуск служб...",
            "done": "Готово!",
            "exiting": "Выход...",
            "goodbye": "До свидания! 🚀",
            "system_restored": "Система восстановлена",
            "language_set": "Язык установлен: ",
        },
        "ar": {
            "app_title": "S I L E N T   P R O   —   N E X U S   E D I T I O N",
            "subtitle": "كود أصلي خالص • 500,000+ حزمة/ث
